### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by bwhm** [Joystream/storage-node-joystream#29]
Please add [this](https://github.com/Joystream/design/blob/master/assets/github/storage-node-joystream-repo.svg) cover.

**Comment by jfinkhaeuser** [comment]
Should I link the asset directly, or copy it over to this repo?

The question can be rephrased as: do you want changes to your design repo to be reflected automatically, or have a manual update in this repo for ever change that should be published?

**Comment by bwhm** [comment]
We have copied to the other non-code repos. Your repo, your decision :)

**Comment by jfinkhaeuser** [comment]
Right, copy it is!
