### ISSUE TITLE
Cannot find module 'bittorrent-dht'

### ISSUE THREAD

**Issue by kamalzaman** [Joystream/storage-node-joystream#43]
I have followed step by step to run storage node. Node version is v10.15.3
I met error when I tried to run command 
`js_storage --key-file 5YourStorageAddress.json`

Here is the output displayed
```
Waiting for the account to be staked as a storage provider role...
Staked, proceeding.
________                     _____
______(_)__________  __________  /__________________ _______ ___
_____  /_  __ \_  / / /_  ___/  __/_  ___/  _ \  __ `/_  __ `__ \
____  / / /_/ /  /_/ /_(__  )/ /_ _  /   /  __/ /_/ /_  / / / / /
___  /  \____/_\__, / /____/ \__/ /_/    \___/\__,_/ /_/ /_/ /_/
/___/         /____/
API server started; API docs at http://localhost:3000/swagger.json
{ Error: Cannot find module 'bittorrent-dht'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/ubuntu/storage-node-joystream/packages/joystream-dht/index.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by bwhm** [comment]
Hey @kamalzaman 
Did you remember to replace `5YourStorageAddress.json` with the `5Something.json` that should have been stated just before what you showed above?

**Comment by kamalzaman** [comment]
Yes, I run it with `js_storage --key-file 5CbhqfnkbQPFwVV1tBopLaQFZmnijBC6ouofEVzHsPKk4qtH.json
`
Is that supposed to be correct?

I am on Ubuntu 16.04

**Comment by bwhm** [comment]
Thanks,
The repo is updating very frequently, so we'll to some debugging. Thanks for reporting the bug, and please check back in when we @ you, either for more info or when we think it's been resolved. This way, you can qualify for a bounty :)

**Comment by kamalzaman** [comment]
Thank you.
I am just a normal user not a developer. So I actually don't expect any bounty with this (maybe) simple bug.
Also tutorial to set up storage node has some errors like typo and command cannot successfully executed for example `sudo apt-get install npm yarn node git`, need extra step workaround. But I guess that's another issue

**Comment by bwhm** [comment]
It is, but thanks anyway. If you make an issue there listing specifics and reference this, it will add to the size of the bounty. It's important to encourage these things!

**Comment by bwhm** [comment]
@kamalzaman 
do you mind trying 
```
$ sudo apt build-essential
$ sudo apt-get update && sudo apt-get upgrade
```
?

**Comment by jfinkhaeuser** [comment]
#44

**Comment by bwhm** [comment]
And `yarn run build` again after above...

**Comment by kamalzaman** [comment]
> @kamalzaman
> do you mind trying
> 
> ```
> $ sudo apt build-essential
> $ sudo apt-get update && sudo apt-get upgrade
> ```
> ?

I have done it in the first place actually. Ok I will try it again

**Comment by bwhm** [comment]
@kamalzaman 
I had the same issue on my mac, but this resolved it:
in `~/storage-node-joystream`

`$ nano package.json`
scroll down to "dependencies", and append as below:
```
    "uuid": "^3.3.2",     #just the comma here
    "bittorrent-dht": "^9.0.0",
    "rpc-websockets": "^4.3.5",
    "sha3": "^2.0.1"
  }
```
save and exit, then:
`$ yarn && yarn run build`
Now it starts for me. 
@mnaamani 
can provide a more elegant solution for you :)

**Comment by jfinkhaeuser** [comment]
None of this should be required, really... very strange. I ran `yarn run build` from a newly checked out repo, and it does the right thing immediately.

**Comment by kamalzaman** [comment]
> @kamalzaman
> I had the same issue on my mac, but this resolved it:
> in `~/storage-node-joystream`
> 
> `$ nano package.json`
> scroll down to "dependencies", and append as below:
> 
> ```
>     "uuid": "^3.3.2",     #just the comma here
>     "bittorrent-dht": "^9.0.0",
>     "rpc-websockets": "^4.3.5",
>     "sha3": "^2.0.1"
>   }
> ```
> save and exit, then:
> `$ yarn && yarn run build`
> Now it starts for me.
> @mnaamani
> can provide a more elegant solution for you :)

Nice. This is working for me. 
`Waiting for the account to be staked as a storage provider role...
Staked, proceeding.
________                     _____
______(_)__________  __________  /__________________ _______ ___
_____  /_  __ \_  / / /_  ___/  __/_  ___/  _ \  __ `/_  __ `__ \
____  / / /_/ /  /_/ /_(__  )/ /_ _  /   /  __/ /_/ /_  / / / / /
___  /  \____/_\__, / /____/ \__/ /_/    \___/\__,_/ /_/ /_/ /_/
/___/         /____/
API server started; API docs at http://localhost:3000/swagger.json
DHT started on port 3060
DHT JSON-RPC service started on port 3090
Sync server started at { address: '::', family: 'IPv6', port: 3030 }
`

**Comment by jfinkhaeuser** [comment]
Actually, took me a while, but I found my mistake. I'll create a fix. Thanks for reporting this!

**Comment by bwhm** [comment]
@kamalzaman feel free to paste your monero address here, or dm me on telegram for your $20 bounty!

**Comment by kamalzaman** [comment]
`45i2SLmNqyojbyo2Cu31rmExqPLf6Ykuk9jYdFKH7PY7QAY9aq3TUwX1SKycRkVaimRZtn5LFXSiHAaQ9JwEXvx67zYUucF`

Thanks @bwhm
