### ISSUE TITLE
Update ContentId class

### ISSUE THREAD

**Issue by siman** [Joystream/storage-node-joystream#58]
Related to https://github.com/Joystream/apps/pull/158

**Comment by jfinkhaeuser** [comment]
Yup, that needs to happen. Or we do the thing we discussed, and make the types their own package.

Also relates to Joystream/apps#91 - whichever happens sooner.

**Comment by jfinkhaeuser** [comment]
The current version of the repo has a `@joystream/runtime-api` package, which should be based on `@joystream/types` when that's published (see #73). Afterwards, it should go into its own repo as per #74 .

I'll close this issue, because it's no longer the most relevant.
