### ISSUE TITLE
Get rid of multiple "repositories" concept in storage node.

### ISSUE THREAD

**Issue by jfinkhaeuser** [Joystream/storage-node-joystream#9]
This is a leftover from a previous misunderstanding, and simplifies the code base, but isn't strictly speaking necessary for Athens.

Either:
- Use a single repository ID, "hardcoded" or in the chain for everything
Or:
- Get rid of multiple repository support before Athens

**Comment by jfinkhaeuser** [comment]
A bit nice to have for the milestone, but useful.

**Comment by jfinkhaeuser** [comment]
Will do this while working on #65

**Comment by mnaamani** [comment]
We no longer have repositories in the storage backend.
