### ISSUE TITLE
Error: No Storage Providers Found?

### ISSUE THREAD

**Issue by blrhc** [Joystream/storage-node-joystream#94]
Moved from https://github.com/Joystream/joystream/issues/118

![No Storage Providers found?](https://user-images.githubusercontent.com/4144334/64913073-db40b900-d6fe-11e9-963b-348635822a28.jpeg)

I have never seen this error before, is it normal?

**Comment by blrhc** [comment]
@bwhm I did try refreshing a number of times. I was trying to play https://testnet.joystream.org/acropolis/pioneer/#/media/play/5ExU4aX6Dr1jjTJ94jTxM674AT6eToVet8ddVgz8eAW4pqEd

**Comment by bwhm** [comment]
Hey,
The `ContentId` for this is `0x7ff2ca7dd5aa7aa9c1307b25366f2e2280002397052710282f8d6278c81e656e`.

A chain state query lets us know that the liason was in fact the Jsgenesis hosted storage node. I tried restarting it now to see if it will then distribute the content. If not, I'm afraid you'll have to re-upload!

*Will watch the vids now btw :)*

**Comment by blrhc** [comment]
Sounds good :)
